/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Produto;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Venda;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.VendaProduto;

import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rodrigo
 */
public class frmCadVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCadVenda
     */
    Venda vendas;
    List<Produto> produtos;
    public frmCadVenda() {
        initComponents();
        
        vendas = new Venda();
        produtos = new LinkedList<>();
        produtos.add(new Produto(1, "Escova de Dentes", "Escova de Dentes", 1.27, 1.00, 0));
        produtos.add(new Produto(2, "Creme Dental", "Creme Dental", 5.00, 4.00, 3));
        produtos.add(new Produto(3, "Fio Dental", "Fio Dental", 3.00, 2.00, 5));
    
        cbxProdutos.removeAllItems();
        for (Produto p : produtos) {
            cbxProdutos.addItem(p);
        }
    }
    
    private void RealizaVenda(){
        lblValor.setText(Double.toString(vendas.getValortotal()));
   
        DefaultTableModel TabelaProdutos = new DefaultTableModel();
        TabelaProdutos.addColumn("Produto");
        TabelaProdutos.addColumn("Quantidade");
        
        
        for (VendaProduto vp : vendas.getProdutos()) {
            Vector v = new Vector();
            v.add(vp.getProduto().getNome());
            v.add(vp.getQuantidade());
            TabelaProdutos.addRow(v);
        }

        tblProdutosAdicionados.setModel(TabelaProdutos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelDadosGerais = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        cbxClientes = new javax.swing.JComboBox();
        lblCliente1 = new javax.swing.JLabel();
        lblDataVenda = new javax.swing.JLabel();
        txtValorVenda = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        PanelProdutos = new javax.swing.JPanel();
        lblProduto = new javax.swing.JLabel();
        cbxProdutos = new javax.swing.JComboBox();
        lblProduto1 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutosAdicionados = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nova Venda");
        setVisible(true);

        lblCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCliente.setText("CLIENTE: ");

        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCliente1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lblDataVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDataVenda.setText("DATA DA VENDA: ");

        lblValorTotal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblValorTotal.setText("VALOR TOTAL:");

        lblValor.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblValor.setText("0,00");

        javax.swing.GroupLayout PanelDadosGeraisLayout = new javax.swing.GroupLayout(PanelDadosGerais);
        PanelDadosGerais.setLayout(PanelDadosGeraisLayout);
        PanelDadosGeraisLayout.setHorizontalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addComponent(lblCliente)
                        .addGap(26, 26, 26)
                        .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addComponent(lblDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorVenda))
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblValor)))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                    .addGap(0, 244, Short.MAX_VALUE)
                    .addComponent(lblCliente1)
                    .addGap(0, 245, Short.MAX_VALUE)))
        );
        PanelDadosGeraisLayout.setVerticalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataVenda)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(lblValor))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                    .addGap(0, 133, Short.MAX_VALUE)
                    .addComponent(lblCliente1)
                    .addGap(0, 132, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Dados Gerais", PanelDadosGerais);

        lblProduto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblProduto.setText("PRODUTO:");

        cbxProdutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblProduto1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblProduto1.setText("QUANTIDADE:");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        tblProdutosAdicionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUTO", "QUANTIDADE", "VALOR UNITARIO", "VALOR TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblProdutosAdicionados);
        tblProdutosAdicionados.getColumnModel().getColumn(0).setHeaderValue("PRODUTO");
        tblProdutosAdicionados.getColumnModel().getColumn(1).setHeaderValue("QUANTIDADE");
        tblProdutosAdicionados.getColumnModel().getColumn(2).setHeaderValue("VALOR UNITARIO");
        tblProdutosAdicionados.getColumnModel().getColumn(3).setHeaderValue("VALOR TOTAL");

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProdutosLayout = new javax.swing.GroupLayout(PanelProdutos);
        PanelProdutos.setLayout(PanelProdutosLayout);
        PanelProdutosLayout.setHorizontalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addComponent(lblProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(txtQuantidade))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(btnAdicionar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemover)
                        .addGap(78, 78, 78))))
        );
        PanelProdutosLayout.setVerticalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", PanelProdutos);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnCadastrar)
                .addGap(73, 73, 73)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja realmente adicionar o item?") == 0) {
            Produto p = (Produto) cbxProdutos.getSelectedItem();
            int qtd = Integer.parseInt(txtQuantidade.getText());
            if (qtd <= 0) {
                JOptionPane.showMessageDialog(rootPane, "Quantidade Inválida. Insira uma quantidade maior que 0!");                       
            } else 
            if (p.getEstoque() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Produto sem Estoque!");
            } else {
                VendaProduto produto = new VendaProduto();
                produto.setProduto(p);
                produto.setQuantidade(qtd);

                vendas.addProdutos(produto);

                JOptionPane.showMessageDialog(rootPane, "Item Adicionado com Sucesso!");

                RealizaVenda();
            } 
        }
        else {
            JOptionPane.showMessageDialog(rootPane, "Item não Adicionado!");
        }
 

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(rootPane, "Deseja remover o item?") == 0) {
             JOptionPane.showMessageDialog(rootPane, "Item Removido com Sucesso!");
             
         }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Finalizar a Venda?") == 0){
            JOptionPane.showMessageDialog(rootPane, "Venda Finalizada com Sucesso!");
            for (VendaProduto vp : vendas.getProdutos()){
                int novoestoque = vp.getProduto().getEstoque() - vp.getQuantidade();
                try {
                    vp.getProduto().setEstoque(novoestoque);
                } catch (Exception ex) {
                    Logger.getLogger(frmCadVenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Finalização da Venda Cancelada!");
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Cancelar a Venda?") == 0){
            JOptionPane.showMessageDialog(rootPane, "Venda Cancelada!");
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDadosGerais;
    private javax.swing.JPanel PanelProdutos;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cbxClientes;
    private javax.swing.JComboBox cbxProdutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblProduto1;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblProdutosAdicionados;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
}
