/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Pagamento;
import javax.swing.JOptionPane;
/**
 *
 * @author Rodrigo
 */
public class frmCadFormaPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCadFormaPagamento
     */
    public frmCadFormaPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblForma = new javax.swing.JLabel();
        txtForma = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFormaPagamento = new javax.swing.JMenu();
        MenuCadastrarForma = new javax.swing.JMenu();

        setTitle("Cadastrar Forma de Pagamento");

        lblForma.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblForma.setText("FORMA DE PAGAMENTO:");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        MenuFormaPagamento.setText("Formas de Pagamento");
        MenuFormaPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuFormaPagamentoMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuFormaPagamento);

        MenuCadastrarForma.setText("Cadastrar Forma de Pagamento");
        jMenuBar1.add(MenuCadastrarForma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblForma, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtForma, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnCadastrar)
                .addGap(69, 69, 69)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblForma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtForma, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCancelar))
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        Pagamento formapagamento = new Pagamento();
        String forma = txtForma.getText();
        formapagamento.setNomeTipo(forma);
        JOptionPane.showMessageDialog(rootPane, "Nova Forma de Pagamento Cadastrada com Sucesso");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void MenuFormaPagamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuFormaPagamentoMouseClicked
        // TODO add your handling code here:
        frmFormasPagamento janelaformapagamento = new frmFormasPagamento();
        janelaformapagamento.setVisible(true);
        add(janelaformapagamento);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_MenuFormaPagamentoMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        frmFormasPagamento janelaformapagamento = new frmFormasPagamento();
        janelaformapagamento.setVisible(true);
        add(janelaformapagamento);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastrarForma;
    private javax.swing.JMenu MenuFormaPagamento;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblForma;
    private javax.swing.JTextField txtForma;
    // End of variables declaration//GEN-END:variables
}
