/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;

/**
 *
 * @author Rodrigo
 */
public class frmFormasPagamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFormasPagamento
     */
    public frmFormasPagamento() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoPagamento = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFormaPagamento = new javax.swing.JMenu();
        MenuCadastrarForma = new javax.swing.JMenu();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formas de Pagamento");
        setToolTipText("");
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblTipoPagamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Cartão"},
                {"Dinheiro"},
                {"Cheque"}
            },
            new String [] {
                "Tipo Pagamento"
            }
        ));
        jScrollPane1.setViewportView(tblTipoPagamento);

        MenuFormaPagamento.setText("Formas de Pagamento");
        jMenuBar1.add(MenuFormaPagamento);

        MenuCadastrarForma.setText("Cadastrar Forma de Pagamento");
        MenuCadastrarForma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCadastrarFormaMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCadastrarForma);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    private void MenuCadastrarFormaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadastrarFormaMouseClicked
        // TODO add your handling code here:
        frmCadFormaPagamento janelaCadFormaPagamento = new frmCadFormaPagamento();
        add(janelaCadFormaPagamento);
        janelaCadFormaPagamento.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarFormaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastrarForma;
    private javax.swing.JMenu MenuFormaPagamento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTipoPagamento;
    // End of variables declaration//GEN-END:variables
}
