/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;


import br.edu.ifnmg.tads.trabalholtp3.DataAccess.EmailDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.EnderecoDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.PessoaDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.TelefoneDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Email;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Endereco;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Pessoa;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Telefone;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Usuario;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Rodrigo
 */
public class frmUsuarios extends javax.swing.JInternalFrame {

    private UsuarioDAO usuariodao;
    private PessoaDAO pessoadao;
    private EmailDAO emaildao;
    private EnderecoDAO enderecodao;
    private TelefoneDAO telefonedao;
    private Usuario usuario;
    private Pessoa pessoa;
    private List<Usuario> usuarios;
    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
        usuariodao = new UsuarioDAO();
        pessoadao = new PessoaDAO();
        enderecodao = new EnderecoDAO();
        emaildao = new EmailDAO();
        telefonedao = new TelefoneDAO();
        
        usuarios = usuariodao.ListarUsuario();
        
        preenchetabela(usuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnRemoverUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        cbxfiltro = new javax.swing.JComboBox();
        txtFiltro = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de Usuários");
        setVisible(true);

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnRemoverUsuario.setText("Remover");
        btnRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUsuarioActionPerformed(evt);
            }
        });

        btnAlterarUsuario.setText("Alterar");
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });

        btnBuscarUsuario.setText("Buscar");
        btnBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUsuarioActionPerformed(evt);
            }
        });

        cbxfiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "RG", "CPF" }));
        cbxfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarUsuario)
                    .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAlterarUsuario)
                        .addGap(35, 35, 35)
                        .addComponent(btnRemoverUsuario)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preenchetabela(List<Usuario> usuarios){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("RG");
        model.addColumn("CPF");
        for (Usuario usuario : usuarios){
            Vector v = new Vector();
            v.add(0, usuario.getCodusuario());
            v.add(1, usuario.getNome());
            v.add(2, usuario.getRg());
            v.add(3, usuario.getCpf());
            model.addRow(v);
        }
        
        tblUsuarios.setModel(model);
    }
    
    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        int codusuario = (int) tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0);
        frmEditarUsuario janela = new frmEditarUsuario(codusuario);
        this.getParent().add(janela);
        janela.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario usuario = new Usuario();
        Pessoa pessoa = new Pessoa();
        try {
            if (cbxfiltro.getSelectedIndex() == 0){
                usuario.setCodusuario(Integer.parseInt(txtFiltro.getText()));
                usuario.setPessoa(pessoa);
            }

            if (cbxfiltro.getSelectedIndex() == 1){
                usuario.setNome(txtFiltro.getText());
                usuario.setPessoa(pessoa);
            }

            if (cbxfiltro.getSelectedIndex() == 2){
                usuario.setRg(txtFiltro.getText());
                usuario.setPessoa(pessoa);
            }

            if (cbxfiltro.getSelectedIndex() == 3){
                usuario.setCpf(Integer.parseInt(txtFiltro.getText()));
                System.out.println(usuario.getCpf());
                usuario.setPessoa(pessoa);
            }

        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

        List<Usuario> Usuarios = usuariodao.buscarUsuarios(usuario);

        preenchetabela(Usuarios);

    }//GEN-LAST:event_btnBuscarUsuarioActionPerformed

    private void cbxfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfiltroActionPerformed

    private void btnRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUsuarioActionPerformed
        // TODO add your handling code here:
        usuarios = usuariodao.ListarUsuario();
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Apagar esse Usuário?") == 0){
        
            int codusuario = (int) tblUsuarios.getValueAt(tblUsuarios.getSelectedRow(), 0);      

            usuario = usuariodao.Abrir(codusuario);
            pessoa = pessoadao.Abrir(usuario.getCodpessoa());  
            pessoa.setEmails(emaildao.Abrir(usuario.getCodpessoa()));
            pessoa.setEnderecos(enderecodao.Abrir(usuario.getCodpessoa()));
            pessoa.setTelefones(telefonedao.Abrir(usuario.getCodpessoa()));

            for (Endereco en : pessoa.getEnderecos()){
                enderecodao.Apagar(en.getCodendereco());
            }    

            for (Telefone tel : pessoa.getTelefones()){
                telefonedao.Apagar(tel.getCodtelefone());
            }

            for (Email em : pessoa.getEmails()){
                emaildao.Apagar(em.getCodemail());
            }

            if (usuariodao.Apagar(usuario.getCodusuario()) && pessoadao.Apagar(pessoa.getCodpessoa())){
                usuarios.remove(usuario);
                JOptionPane.showMessageDialog(rootPane, "Usuário Removido com sucesso");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada");
        }
        
        preenchetabela(usuarios);
    }//GEN-LAST:event_btnRemoverUsuarioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JComboBox cbxfiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
