/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.VendaDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.VendaProdutoDAO;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Cliente;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Pagamento;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Usuario;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Venda;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.VendaProduto;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rodrigo
 */
public class frmVendas extends javax.swing.JInternalFrame {
    private VendaProdutoDAO vendaprodutodao;
    private VendaDAO vendadao;
    private Venda venda;
    private Pagamento pagamento;
    private Produto produto;
    private Cliente cliente;
    private Usuario usuario;
    private List<VendaProduto> itens;
    private List<Venda> vendas;
    
    
    /**
     * Creates new form frmVendas
     */
    public frmVendas() {
        initComponents();
        vendadao = new VendaDAO();
        vendaprodutodao = new VendaProdutoDAO();
        vendas = vendadao.listarVendas();
        preenchetabela(vendas);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void preenchetabela(List<Venda> vendas){
        DefaultTableModel tabelavenda = new DefaultTableModel();
        tabelavenda.addColumn("Código Venda");
        tabelavenda.addColumn("Nome Cliente");
        tabelavenda.addColumn("Nome Usuario");
        tabelavenda.addColumn("Forma de Pagamento");
        tabelavenda.addColumn("Valor da Venda");
        for (Venda venda : vendas){
            double valor = 0;
            Vector v =  new Vector();
            itens = vendaprodutodao.ListarItens(venda.getCodvenda());
            
            for (VendaProduto vendaproduto : itens){
                valor = valor + (vendaproduto.getQuantidade() * vendaproduto.getProduto().getValorunitariovenda());
            }
            
            v.add(venda);
            v.add(venda.getCliente());
            v.add(venda.getUsuario());
            v.add(venda.getPagamento());
            v.add(valor);
            tabelavenda.addRow(v);
        }
        
        tblVendas.setModel(tabelavenda);
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        cbxfiltro = new javax.swing.JComboBox();
        btnBuscarVenda = new javax.swing.JButton();
        btnVisualizaVenda = new javax.swing.JButton();
        btnRemoverVenda = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Vendas");
        setVisible(true);

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código da Venda", "Nome Cliente", "Nome Usuário", "Forma de Pagamento", "Valor da Venda"
            }
        ));
        jScrollPane1.setViewportView(tblVendas);

        cbxfiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Cliente", "Usuário", "Forma de Pagamento" }));
        cbxfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfiltroActionPerformed(evt);
            }
        });

        btnBuscarVenda.setText("Buscar");
        btnBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVendaActionPerformed(evt);
            }
        });

        btnVisualizaVenda.setText("Visualizar");
        btnVisualizaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizaVendaActionPerformed(evt);
            }
        });

        btnRemoverVenda.setText("Remover");
        btnRemoverVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoverVenda))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnVisualizaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarVenda))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnVisualizaVenda)
                        .addGap(35, 35, 35)
                        .addComponent(btnRemoverVenda)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfiltroActionPerformed

    private void btnBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendaActionPerformed
        // TODO add your handling code here:
        venda = new Venda();
        cliente = new Cliente();
        usuario = new Usuario();
        pagamento = new Pagamento();
        venda.setCliente(cliente);
        venda.setUsuario(usuario);
        venda.setPagamento(pagamento);
        try {   
            if (cbxfiltro.getSelectedIndex() == 0){
                venda.setCodvenda(Integer.parseInt(txtFiltro.getText()));
                System.out.print(venda);
            }

            if (cbxfiltro.getSelectedIndex() == 1){
                cliente = new Cliente();
                cliente.setNome(txtFiltro.getText());
                venda.setCliente(cliente);
            }

            if (cbxfiltro.getSelectedIndex() == 2){
                usuario = new Usuario();
                usuario.setNome(txtFiltro.getText());
                venda.setUsuario(usuario);
            }

            if (cbxfiltro.getSelectedIndex() == 3){
                pagamento = new Pagamento();
                pagamento.setNomeTipo(txtFiltro.getText());
                venda.setPagamento(pagamento);
            }

        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

        vendas = vendadao.buscarVendas(venda);

        preenchetabela(vendas);
    }//GEN-LAST:event_btnBuscarVendaActionPerformed

    private void btnVisualizaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizaVendaActionPerformed
        // TODO add your handling code here:
        Venda venda = (Venda) tblVendas.getValueAt(tblVendas.getSelectedRow(), 0);
        frmVisualizaVenda janela = new frmVisualizaVenda(venda.getCodvenda());
        this.getParent().add(janela);
        janela.setVisible(true);
        this.setVisible(false);
         
    }//GEN-LAST:event_btnVisualizaVendaActionPerformed

    private void btnRemoverVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverVendaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Apagar essa Venda?") == 0){

           Venda venda = (Venda) tblVendas.getValueAt(tblVendas.getSelectedRow(), 0);
            
            if (vendadao.Apagar(venda.getCodvenda()) && vendaprodutodao.Apagar(venda.getCodvenda())){
                vendas.remove(venda);
                JOptionPane.showMessageDialog(rootPane, "Venda Apagada com sucesso");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ação cancelada");
        }

        preenchetabela(vendas);
    }//GEN-LAST:event_btnRemoverVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarVenda;
    private javax.swing.JButton btnRemoverVenda;
    private javax.swing.JButton btnVisualizaVenda;
    private javax.swing.JComboBox cbxfiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
