/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalholtp3.InterfaceUsuario;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.ClienteDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.FormaPagamentoDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.ProdutoDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.VendaDAO;
import br.edu.ifnmg.tads.trabalholtp3.DataAccess.VendaProdutoDAO;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Cliente;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.ErroValidacaoException;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Pagamento;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Produto;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Usuario;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.Venda;
import br.edu.ifnmg.tads.trabalholtp3.DomainModel.VendaProduto;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rodrigo
 */
public class frmVisualizaVenda extends javax.swing.JInternalFrame {
    private VendaProdutoDAO vendaprodutodao;
    private VendaDAO vendadao;
    private Venda venda;
    private Produto produto;
    private List<VendaProduto> itens;
    /**
     * Creates new form frmVisualizaVenda
     */
    public frmVisualizaVenda(int codvenda) {
        initComponents();
        vendadao = new VendaDAO();
        vendaprodutodao = new VendaProdutoDAO();
        venda = vendadao.Abrir(codvenda);
        itens = vendaprodutodao.ListarItens(codvenda);
        carregadadosvenda();
        carregatabela(itens);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelDadosGerais = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        lblDataVenda = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblFormasPagamento = new javax.swing.JLabel();
        lblUsuarioVenda = new javax.swing.JLabel();
        lblClienteVenda = new javax.swing.JLabel();
        lblFormaPagamentoVenda = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        PanelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutosAdicionados = new javax.swing.JTable();
        lblEstoqueProduto = new javax.swing.JLabel();
        lblValorUnitarioProduto = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        cbxfiltro = new javax.swing.JComboBox();
        btnBuscarItem = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Visualiza Venda");

        lblCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblCliente.setText("CLIENTE: ");

        lblCliente1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lblDataVenda.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblDataVenda.setText("DATA DA VENDA: ");

        lblValorTotal.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblValorTotal.setText("VALOR TOTAL:");

        lblValor.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblValor.setText("0,00");

        lblUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblUsuario.setText("USUARIO: ");

        lblFormasPagamento.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblFormasPagamento.setText("FORMA DE PAGAMENTO:");

        lblUsuarioVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblClienteVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblFormaPagamentoVenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblData.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelDadosGeraisLayout = new javax.swing.GroupLayout(PanelDadosGerais);
        PanelDadosGerais.setLayout(PanelDadosGeraisLayout);
        PanelDadosGeraisLayout.setHorizontalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosGeraisLayout.createSequentialGroup()
                                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                                        .addComponent(lblCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(lblClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosGeraisLayout.createSequentialGroup()
                                        .addComponent(lblUsuario)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblUsuarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addComponent(lblValor, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                                .addComponent(lblDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                        .addComponent(lblFormasPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormaPagamentoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                    .addGap(0, 364, Short.MAX_VALUE)
                    .addComponent(lblCliente1)
                    .addGap(0, 365, Short.MAX_VALUE)))
        );
        PanelDadosGeraisLayout.setVerticalGroup(
            PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsuarioVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDadosGeraisLayout.createSequentialGroup()
                        .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormasPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaPagamentoVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(lblDataVenda))
                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorTotal)
                    .addComponent(lblValor))
                .addGap(72, 72, 72))
            .addGroup(PanelDadosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelDadosGeraisLayout.createSequentialGroup()
                    .addGap(0, 206, Short.MAX_VALUE)
                    .addComponent(lblCliente1)
                    .addGap(0, 207, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Dados Gerais", PanelDadosGerais);

        tblProdutosAdicionados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PRODUTO", "QUANTIDADE", "VALOR UNITARIO", "VALOR TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblProdutosAdicionados);

        lblEstoqueProduto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lblValorUnitarioProduto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        cbxfiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome do Produto" }));
        cbxfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfiltroActionPerformed(evt);
            }
        });

        btnBuscarItem.setText("Buscar");
        btnBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProdutosLayout = new javax.swing.GroupLayout(PanelProdutos);
        PanelProdutos.setLayout(PanelProdutosLayout);
        PanelProdutosLayout.setHorizontalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProdutosLayout.createSequentialGroup()
                                .addComponent(lblEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(132, Short.MAX_VALUE))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblValorUnitarioProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(203, Short.MAX_VALUE))))
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(231, 231, 231))))
        );
        PanelProdutosLayout.setVerticalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarItem)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValorUnitarioProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Produtos", PanelProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void carregatabela(List<VendaProduto> itens){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código Item");
        model.addColumn("Produto");
        model.addColumn("Quantidade");
        model.addColumn("Valor Unitário");
        model.addColumn("Valor Total");
       
        for (VendaProduto vp : itens) {
            Vector v = new Vector();
            v.add(vp);
            v.add(vp.getProduto().getNome());
            v.add(vp.getQuantidade());
            v.add(vp.getProduto().getValorunitariovenda());
            v.add(vp.getProduto().getValorunitariovenda() * vp.getQuantidade());
            model.addRow(v);
        }

        tblProdutosAdicionados.setModel(model);
    }
    
    private void carregadadosvenda(){
        double valortotalvenda = 0;
        
        lblClienteVenda.setText(venda.getCliente().getNome());
        lblUsuarioVenda.setText(venda.getUsuario().getNome());
        lblFormaPagamentoVenda.setText(venda.getPagamento().getNomeTipo());
        
        for (VendaProduto vp : itens) {
            valortotalvenda = valortotalvenda + (vp.getProduto().getValorunitariovenda() * vp.getQuantidade());
        }
        
        
        lblValor.setText(Double.toString(valortotalvenda));
    }
    
    private void cbxfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfiltroActionPerformed

    private void btnBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarItemActionPerformed
        // TODO add your handling code here:
        VendaProduto item = new VendaProduto();
        produto = new Produto();
        item.setProduto(produto);
        item.setVenda(venda);
        try {
            if (cbxfiltro.getSelectedIndex() == 0){
                item.setCodvendaproduto(Integer.parseInt(txtFiltro.getText()));
            }

            if (cbxfiltro.getSelectedIndex() == 1){
                produto = new Produto();
                produto.setNome(txtFiltro.getText());
                item.setProduto(produto);
            }
            
        } catch (ErroValidacaoException ex) {
            Logger.getLogger(frmVisualizaVenda.class.getName()).log(Level.SEVERE, null, ex);
        }

        itens = vendaprodutodao.BuscarItens(item);

       carregatabela(itens);
        
    }//GEN-LAST:event_btnBuscarItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDadosGerais;
    private javax.swing.JPanel PanelProdutos;
    private javax.swing.JButton btnBuscarItem;
    private javax.swing.JComboBox cbxfiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblClienteVenda;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataVenda;
    private javax.swing.JLabel lblEstoqueProduto;
    private javax.swing.JLabel lblFormaPagamentoVenda;
    private javax.swing.JLabel lblFormasPagamento;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuarioVenda;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorUnitarioProduto;
    private javax.swing.JTable tblProdutosAdicionados;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
